
from typing import TYPE_CHECKING
from appium import webdriver
# :return: A string of test URL
SERVER_URL_BASE = 'http://localhost:4723/wd/hub'

if TYPE_CHECKING:
    from appium.webdriver.webdriver import WebDriver


def appium_command(command: str) -> str:
    """Return a command of Appium
    Returns:
        str: A string of command URL
    """
    return f'{SERVER_URL_BASE}{command}'


def android_driver() -> 'WebDriver':
    """Return a W3C driver which is generated by a mock response for Android
    Returns:
        `webdriver.webdriver.WebDriver`: An instance of WebDriver
    """
    desired_caps = {
        'platformName': 'Android',
        'appPackage': 'io.kiwiplus.app.kiwiplay.stage',
        'noReset': 'true',
        'fullReset': 'false'
    }

    driver = webdriver.Remote(SERVER_URL_BASE, desired_caps)
    driver.implicitly_wait(30)
    return driver
